### ISSUE TITLE
Could not save tmp file for attachment in mail

### ISSUE THREAD

**Issue by Maxime-Vacossin** [dereuromark/cakephp-feedback#12]
Hi ! 

We try to use CakePhp FeedBack and we are facing an issue with the mail attachments.

![image](https://user-images.githubusercontent.com/57619142/92723684-b743a200-f369-11ea-843e-4fde2846eb37.png)

The plugin allow us to submit feedbacks but throw an error with the file_put_contents method for email attachments.

We have the **app_feedback.php** file with the initial value : 
```php
'configuration' => [
            FilesystemStore::NAME => [
                'location' => ROOT . DS . 'tmp' . DS . 'feedback' . DS,
            ],
```

In the file /vendor/dereuromark/cakephp-feedback/src/Model/Table/FeedbackstoreTable.php, in the function mail(), we have those lines : 

```php
        $tmpfile = APP . 'tmp' . DS . time() . '_' . mt_rand(1000, 9999) . '.png';

        if (!file_put_contents($tmpfile, base64_decode($feedbackObject['screenshot']))) {
            //Need to save tmp file
            throw new NotFoundException('Could not save tmp file for attachment in mail');
        }
```

In CakePhp config/path.php file, we have : 
```php
/*
 * Path to the application's directory.
 */
define('APP', ROOT . DS . APP_DIR . DS);
```

The tmp folder path is not supose to be `ROOT . DS . 'tmp'` ?
```diff
- $tmpfile = APP . 'tmp' . DS . time() . '_' . mt_rand(1000, 9999) . '.png';
+ $tmpfile = ROOT . DS . 'tmp' . DS . time() . '_' . mt_rand(1000, 9999) . '.png';
```

For the moment, I'm trying to understand why the email is not send.
With the updated tmp folder path, the error is not throw anymore but I didn't receive the email.

If you have any idea that could help us, you're welcome !
Thanks in advance !

**Comment by dereuromark** [comment]
Yes, please provide a PR with the fix for the path.

**Comment by Maxime-Vacossin** [comment]
Done !
But I do not know why my file is not save in the folder.. And the mail function end with the log "Feedback could not be stored".

**Comment by dereuromark** [comment]
So you still have some troubles there?

**Comment by Maxime-Vacossin** [comment]
Yes, the `file_put_contents` function do not throw exceptions anymore but the png file is not in the folder.. 

The `setAttachment` method try to add a file to the mail but the file could not be found.


```php
                try {
			$email->send($feedbackObject['feedback']);
			$returnobject['result'] = true;
			$returnobject['msg'] = __d('feedback', 'Thank you. Your feedback was saved.');

			return $returnobject;
		} catch (Exception $e) {
			// Something went wrong, lets try to log it
			Log::write('error', 'Feedback could not be stored (' . $e->getMessage() . '): ' . json_encode($feedbackObject));
		}
```

In the error.log file, I have this log : 

```log
Error: Feedback could not be stored (Mail Cake\Mailer\Mailer::<p>A copy of your submitted feedback:</p>maxime@iteracode.fr<p>Browser: Chrome 84.0.4147.125<br/>Url: http://irfa.test/admin/formations/<br/>OS: MacOS<br/>By: tyest test<br/>Screenshot: <br/></p><img src="cid:id-screenshot">() could not be found, or is not accessible.): 
```

**Comment by dereuromark** [comment]
If you can fix it please PR that fix.

**Comment by Maxime-Vacossin** [comment]
It's sorcery sir ...

This is my tests : 

Initial code :
```php
        $tmpfile = TMP . 'feedback' . DS . time() . '_' . mt_rand(1000, 9999) . '.png';

        if (!file_put_contents($tmpfile, base64_decode($feedbackObject['screenshot']))) {
            //Need to save tmp file
            throw new NotFoundException('Could not save tmp file for attachment in mail');
        }
```

This diff is working and save the file :
```diff
-        $tmpfile = TMP . 'feedback' . DS . time() . '_' . mt_rand(1000, 9999) . '.png';

-        if (!file_put_contents($tmpfile, base64_decode($feedbackObject['screenshot']))) {
+        if (!file_put_contents(TMP . 'feedback' . DS . time() . '_' . mt_rand(1000, 9999) . '.png', base64_decode($feedbackObject['screenshot']))) {
            //Need to save tmp file
            throw new NotFoundException('Could not save tmp file for attachment in mail');
        }
```

Or this one :
```diff
        $tmpfile = TMP . 'feedback' . DS . time() . '_' . mt_rand(1000, 9999) . '.png';

-        if (!file_put_contents($tmpfile, base64_decode($feedbackObject['screenshot']))) {
+        if (!file_put_contents($tmpfile . 'something', base64_decode($feedbackObject['screenshot']))) {
            //Need to save tmp file
            throw new NotFoundException('Could not save tmp file for attachment in mail');
        }
```


I do not know why .. Using `$tmpfile` variable in the file_put_contents method is not working .. But if you concat the variable with something, this is working ... It's sorcery to me ..

I'am the only one facing this issue ? 


Edit : 

I've try this code : 
```php
        $content = base64_decode($feedbackObject['screenshot']);
        $file = fopen($tmpfile, "wb");
        fwrite($file, $content);
        fclose($file);
```

And i'm facing the same issue .. If I use `$tmpfile . 'something`, it's working .. If I don't, the file isn't saved..

**Comment by dereuromark** [comment]
Please note:
I added a DB backend instead of plain file handling.
This also includes a status and a priority field.

So in general, going this way might already solve a lot of issues, including pagination/filterung of existing entries.
An import from files to this one is also included now.
